[project]
authors = ["Ratul Buragohain <ratul75@hotmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "llmlite.mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
